sudo: required
language: node_js
node_js:
  - "node"
cache:
  directories:
  - node_modules
branches:
  only:
    - master
    - develop
install:
  - npm install
script:
  - npm run test:ci
  - npm run build
deploy:  
  on:
    branch: master
  provider: s3
  access_key_id: $AWS_ACCESS_ID
  secret_access_key: $AWS_ACCESS_SECRET
  bucket: ims-reactts
  local_dir: build
  skip_cleanup: true
  region: ap-southeast-1

